sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - docker-compose up

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push fbbc/sem3project-backend;
    fi