sudo: required

language: java
jdk: oraclejdk8

#Maven Cache
cache:
  directories:
  - $HOME/.m2

services:
  - docker

stages:
  - unit-test
  - api-test-Deploy

before_install:
  - env | grep -E '^PROP_' > .env

jobs:
  include:
    - stage: unit-test
      script:
       - mvn test -DtestGroup=org/cba
    - stage: api-test-Deploy
      script:
       - mvn war:exploded
       - docker-compose up -d
       - mvn test -DtestGroup=api -Dserver.port=5001
       - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          docker push fbbc/sem3project-backend;
          fi