sudo: required

language: java
jdk: oraclejdk8

#Maven Cache
cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_install:
  - mvn war:exploded
  - docker-compose up -d

script:
  - mvn test -DtestGroup=org/cba
  - mvn test -DtestGroup=api -Dserver.port=5001

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push fbbc/sem3project-backend;
    fi