version: '3'

services:
  holiday-service:
    build: .
    env_file: .env
    image: fbbc/sem3project-backend
    ports:
     - 5001:8080
    depends_on:
     - mysql
    volumes:
     - ./img:/home/img

  mysql:
    image: mysql:5.6.26
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PROP_DB_PASSWORD}
      MYSQL_DATABASE: cba_sem3project